import type { NextPage } from "next";
import Head from "next/head";
import Article from "../components/Article";
import ArticleDetails from "../components/ArticleDetails";
import Comment from "../components/Comment";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Article
          details={{
            title: "Title",
            content: "Hellow people",
            upvotes: 10,
            downvotes: 20,
            date: new Date().toString(),
            username: "Emi",
          }}
          comments={[
            {
              content: "Hellow people",
              upvotes: 10,
              downvotes: 20,
              date: new Date().toString(),
              username: "Emi",
            },
          ]}
        />
        {/* <Comment
          content="Hellow people"
          upvotes={10}
          downvotes={20}
          date={new Date().toString()}
          username="Emi"
        />
        <ArticleDetails
          title="Title"
          content="Hellow people"
          upvotes={10}
          downvotes={20}
          date={new Date().toString()}
          username="Emi"
        /> */}
      </main>
    </div>
  );
};

export default Home;
