import type { NextPage } from "next";
import Head from "next/head";
import { useArticles } from "../api/hooks";
import Article from "../components/Article";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, error, loading } = useArticles();
  if (loading) return <div>loading...</div>;

  const articles = (data as any).data.children;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {articles.map((article: any) => (
          <Article
            key={article.data.name}
            details={{
              title: article.data.title,
              content: article.data.selftext,
              score: article.data.score,
              date: article.data.created_utc,
              username: article.data.author,
            }}
            comments={[]}
          />
        ))}
      </main>
    </div>
  );
};

export default Home;
